# Configuration of the cloud, uses specs.yaml

data-centers:
    -   name: data-center-1
        servers:
            -   name: server-type-1
                count: 1
                scheduler: greedy
            -   name: server-type-2
                count: 1
                scheduler: greedy
    -   name: data-center-2
        servers:
            -   name: server-type-1
                count: 1
                scheduler: greedy
            -   name: server-type-2
                count: 1
                scheduler: greedy
