# List of server specs, used in cloud.yaml

-   name: server-type-1
    ram: 32
    io-bandwidth: 2000
    cores-count: 16
-   name: server-type-2
    ram: 16
    io-bandwidth: 3000
    cores-count: 8
